# Generated by Django 5.1.6 on 2025-02-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdata',
            old_name='contact',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='country',
            new_name='email',
        ),
    ]
