# Generated by Django 5.1.6 on 2025-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_contact_logdata_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
